# Generated by Django 5.2.4 on 2026-03-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_bookmarks_profile_embedding_profile_views_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created']},
        ),
    ]
