# Generated by Django 6.0.1 on 2026-03-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('owner', 'name')},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
    ]
