# Generated by Django 6.0.1 on 2026-03-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_skill_unique_together_remove_skill_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set(),
        ),
    ]
