# Generated by Django 5.2.4 on 2026-03-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_skill_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image_content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
