# Generated by Django 6.0.1 on 2026-03-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image_content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
